/*
 * Copyright (c) 2026. Dick Lieber, WA9NNN
 *
 * This program is free software: you can redistribute it and/or modify 
 * it under the terms of the GNU General Public License as published by 
 * the Free Software Foundation, either version 3 of the License, or    
 * (at your option) any later version.                                  
 *                                                                      
 * This program is distributed in the hope that it will be useful,      
 * but WITHOUT ANY WARRANTY; without even the implied warranty of       
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the        
 * GNU General Public License for more details.                         
 *                                                                      
 * You should have received a copy of the GNU General Public License    
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

/*
 * Copyright (c) 2025-2026. Dick Lieber, WA9NNN
 *
 * This program is free software: you can redistribute it and/or modify 
 * it under the terms of the GNU General Public License as published by 
 * the Free Software Foundation, either version 3 of the License, or    
 * (at your option) any later version.                                  
 *                                                                      
 * This program is distributed in the hope that it will be useful,      
 * but WITHOUT ANY WARRANTY; without even the implied warranty of       
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the        
 * GNU General Public License for more details.                         
 *                                                                      
 * You should have received a copy of the GNU General Public License    
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

package ics205.util

import org.apache.commons.lang3.Conversion

import java.nio.ByteBuffer
import java.util
import java.util.{Base64, UUID}
import java.util.concurrent.atomic.AtomicInteger

/**
 * An ID based on UUID but in a compact form.
 */
object Ids:
  /**
   * Unit tests can set to true to get sequential, predictable Ids.
   */
  private var sequentialIds: Option[AtomicInteger] = None

  def useSeqentialStartingAt(start: Int = 0): Unit =
    sequentialIds = Some(new AtomicInteger(start))

  def useSequentialStartingAt(start: Int = 0): Unit =
    useSeqentialStartingAt(start)

  def revertToRandom(): Unit =
    sequentialIds = None

  /**
   * Create a compact, url-safe, representation of a UUID.
   *
   * @return
   */
  def generateId(): Id =
    sequentialIds match
      case Some(sequentialIds) =>
        sequentialIds.getAndIncrement().toString
      case None =>
        nextRandom

  /**
   * Create an ID shorter than one generated by Ids.generateId.
   * Id consists of a 18 bit value as 3 base64 characters.
   *
   * @return
   */
  def generateInstanceId(): Id =
    val randomInt = scala.util.Random.nextInt(1 << 18)
    val bb = ByteBuffer.allocate(4)
    bb.putInt(randomInt << 8) // Shift to make the 18 bits more accessible or just use the bytes
    val bytes = bb.array().take(3)
    // We only need 18 bits for 3 base64 characters. 3 bytes is 24 bits.
    // Base64 of 2 bytes (16 bits) is 3 chars with padding, or 3 chars without padding if we are careful.
    // 2 bytes = 16 bits. 16/6 = 2.66 -> 3 chars.
    // Let's use 2 bytes to get exactly 3 chars without padding.
    val twoBytes = bb.array().slice(1, 3) 
    Base64.getUrlEncoder
      .withoutPadding()
      .encodeToString(twoBytes)

  def nextRandom: Id =
    val uuid = UUID.randomUUID
    val bb = ByteBuffer.allocate(16)
    bb.putLong(uuid.getMostSignificantBits)
    bb.putLong(uuid.getLeastSignificantBits)
    val bytes = bb.array()
    Base64.getUrlEncoder
      .withoutPadding()
      .encodeToString(bytes)



  type Id = String
  val IdSize = 22